apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: fmtok8s-auth
spec:
  kvVersion: 1
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: fmtok8s-role
  data:
  - name: username
    key: secret/data/fmtok8s